base_topology: scalefree
connection_parameter: 2
dataset_base: ../pcn-topologies/datasets/
force: true
id: '69'
log_level: error
min_channel_balance: 0
multiplier_probability: 0.25
name: id69-synthetic-poisson-nodes-10000-txs-pareto-100000-scalefree2-mult-0.75-prob-0.25
node_count: 10000
nographcalcs: false
noplots: false
showtopology: false
specfile: null
tx_count: 100000
tx_inclusion_probability: 1.0
tx_participant_distribution: poisson
tx_value_distribution: pareto
value_multiplier: 0.75
