#!/usr/bin/env python3

import argparse
from PCNGraph.graph_analysis import *

parser = argparse.ArgumentParser()
parser.add_argument('-base', required=True, help='The directory of data files')
parser.add_argument('-method', required=True, help='The method for selecting nodes in the graph')
parser.add_argument('-n', required=True, type=int, help='The number of nodes to select')
args = parser.parse_args()

nodes, dominances = select_n_by_method(args.base, method=args.method, top_n=args.n)
with open(args.base + '/' + betweenness_centrality + ".txt", "w") as f:
    f.write(str(nodes))
    
with open(args.base + '/' + "central_point_dominances.txt", "w") as f:
    for d in dominances:
        f.write(str(d) + "\n")
