base_topology: scalefree
connection_parameter: 2
force: false
id: '42'
log_level: error
min_channel_balance: 100
multiplier_probability: 1.0
name: id42-synthetic-poisson-nodes-100-txs-pareto-100-scalefree2-mult-1.0-prob-1.0-min100
node_count: 100
nographcalcs: false
noplots: false
showtopology: false
specfile: null
tx_count: 100
tx_inclusion_probability: 1.0
tx_participant_distribution: poisson
tx_value_distribution: pareto
value_multiplier: 1.0
