base_topology: scalefree
connection_parameter: 2
force: true
id: '68'
log_level: error
min_channel_balance: 0
multiplier_probability: 0.5
name: id68-synthetic-random-nodes-10000-txs-pareto-100000-scalefree2-mult-0.5-prob-0.5
node_count: 10000
nographcalcs: false
noplots: false
showtopology: false
specfile: null
tx_count: 100000
tx_inclusion_probability: 1.0
tx_participant_distribution: random
tx_value_distribution: pareto
value_multiplier: 0.5
