base_topology: random
connection_parameter: 0.001
force: false
id: '65'
log_level: error
min_channel_balance: 50
multiplier_probability: 1.0
name: id65-synthetic-poisson-nodes-100-txs-exponential-100-random0.001-mult-1.0-prob-1.0-min50
node_count: 100
nographcalcs: false
noplots: false
showtopology: false
specfile: null
tx_count: 100
tx_inclusion_probability: 1.0
tx_participant_distribution: poisson
tx_value_distribution: exponential
value_multiplier: 1.0
