base_topology: scalefree
connection_parameter: 2
force: true
id: '51'
log_level: error
min_channel_balance: 100
multiplier_probability: 1.0
name: id51-synthetic-poisson-nodes-10000-txs-poisson-100000-scalefree2-mult-1.0-prob-1.0-min100
node_count: 10000
nographcalcs: false
noplots: false
showtopology: false
specfile: null
tx_count: 100000
tx_inclusion_probability: 1.0
tx_participant_distribution: poisson
tx_value_distribution: poisson
value_multiplier: 1.0
