base_topology: scalefree
connection_parameter: 2
force: true
id: '60'
log_level: error
min_channel_balance: 100
multiplier_probability: 1.0
name: id60-synthetic-poisson-nodes-100-txs-exponential-100-scalefree2-mult-1.0-prob-1.0-min100
node_count: 100
nographcalcs: false
noplots: false
showtopology: false
specfile: null
tx_count: 100
tx_inclusion_probability: 1.0
tx_participant_distribution: poisson
tx_value_distribution: exponential
value_multiplier: 1.0
