base: ../data/dynamic-id25-23/
cumsum: true
legend_loc:
- 0.68
- 0.65
lines:
- line:
    base: ../dynamic-id25-22/dynamic-id25-synthetic-poisson-nodes-10k-txs-pareto-100k-scalefree2-mult-0.5-prob-0.5-speedymurmurs-3-1-1-lat1ms-concurrent-10000-griefing_success-10000ms/READABLE_FILE_SM-P0-10000/0/CREDIT_NETWORK-SM-P0-1.0-TREE_ROUTE_TDRAP-true-false-3-0.002-RANDOM_PARTITIONER-1/
    files:
    - cnet-totalCreditTransacted.txt
    name: 0% attackers
- line:
    base: dynamic-id25-synthetic-poisson-nodes-10k-txs-pareto-100k-scalefree2-mult-0.5-prob-0.5-speedymurmurs-3-1-1-lat30ms-concurrent-10000-drop_all-selected-10-drop_all-10000ms/READABLE_FILE_SM-P0-10000/0/CREDIT_NETWORK-SM-P0-1.0-TREE_ROUTE_TDRAP-true-false-3-0.002-RANDOM_PARTITIONER-1/
    files:
    - cnet-totalCreditTransacted.txt
    name: 0.1% attacker
- line:
    base: dynamic-id25-synthetic-poisson-nodes-10k-txs-pareto-100k-scalefree2-mult-0.5-prob-0.5-speedymurmurs-3-1-1-lat30ms-concurrent-10000-drop_all-selected-50-drop_all-10000ms/READABLE_FILE_SM-P0-10000/0/CREDIT_NETWORK-SM-P0-1.0-TREE_ROUTE_TDRAP-true-false-3-0.002-RANDOM_PARTITIONER-1/
    files:
    - cnet-totalCreditTransacted.txt
    name: 0.5% attacker
- line:
    base: dynamic-id25-synthetic-poisson-nodes-10k-txs-pareto-100k-scalefree2-mult-0.5-prob-0.5-speedymurmurs-3-1-1-lat30ms-concurrent-10000-drop_all-selected-100-drop_all-10000ms/READABLE_FILE_SM-P0-10000/0/CREDIT_NETWORK-SM-P0-1.0-TREE_ROUTE_TDRAP-true-false-3-0.002-RANDOM_PARTITIONER-1/
    files:
    - cnet-totalCreditTransacted.txt
    name: 1% attacker
- line:
    base: dynamic-id25-synthetic-poisson-nodes-10k-txs-pareto-100k-scalefree2-mult-0.5-prob-0.5-speedymurmurs-3-1-1-lat30ms-concurrent-10000-drop_all-selected-300-drop_all-10000ms/READABLE_FILE_SM-P0-10000/0/CREDIT_NETWORK-SM-P0-1.0-TREE_ROUTE_TDRAP-true-false-3-0.002-RANDOM_PARTITIONER-1/
    files:
    - cnet-totalCreditTransacted.txt
    name: 3% attacker
- line:
    base: dynamic-id25-synthetic-poisson-nodes-10k-txs-pareto-100k-scalefree2-mult-0.5-prob-0.5-speedymurmurs-3-1-1-lat30ms-concurrent-10000-drop_all-selected-500-drop_all-10000ms/READABLE_FILE_SM-P0-10000/0/CREDIT_NETWORK-SM-P0-1.0-TREE_ROUTE_TDRAP-true-false-3-0.002-RANDOM_PARTITIONER-1/
    files:
    - cnet-totalCreditTransacted.txt
    name: 5% attacker
plotname: exp 23; SpeedyMurmurs; dataset 25
running_avg: 1500
xlabel: Time Epochs
xmin: 0
ylabel: Successful Transaction Values
ymin: 0
