base_topology: random
connection_parameter: 0.001
force: false
id: '46'
log_level: error
min_channel_balance: 0
multiplier_probability: 1.0
name: id46-synthetic-poisson-nodes-100-txs-pareto-100-random0.001-mult-1.0-prob-1.0
node_count: 100
nographcalcs: false
noplots: false
showtopology: false
specfile: null
tx_count: 100
tx_inclusion_probability: 1.0
tx_participant_distribution: poisson
tx_value_distribution: pareto
value_multiplier: 1.0
