#!/usr/bin/env python3

import argparse
import os
from os import listdir
from os.path import isdir, realpath, dirname
import sys
from glob import glob
import pprint

script_dir = dirname(realpath(__file__))

# This line is required so I can use the pcn module
sys.path.append(script_dir + '/../')
import pcn

if __name__ == "__main__":

    metric_file_mapping = {'success_ratio':{'ylabel':'Success Ratio',
                                            'xlabel':'Time Epochs',                                            
                                            'x_range':[0, 60000],
                                            'y_range':[0.0, 1.0],
                                            'filename': 'cnet-succR.txt'}}

    parser = argparse.ArgumentParser()
    parser.add_argument('--experiment', '--exp', required=True,
                        help='The experiment ID')
    parser.add_argument('--dataset', '--ds', required=True,
                        help='The dataset ID')    
    parser.add_argument('--algorithm', required=False, default='all',
                        choices=['all', 'speedymurmurs', 'maxflow'],
                        help='The routing algorithm to plot')
    parser.add_argument('--basepath', required=False, default=script_dir + '/../data/',
                        help='The path to the experiment data directory')
    parser.add_argument('--metric', required=False, choices=['success_ratio'],
                        default='success_ratio', help='The metric to plot')
    parser.add_argument('--xlabel', required=False, default=None,
                        help='The x-axis label')
    parser.add_argument('--ylabel', required=False, default=None,
                        help='The y-axis label')
    parser.add_argument('--running_avg', required=False, default=1500,
                        help='The running average of the plot')
    parser.add_argument('--legend', nargs='+', required=False, default=[],
                        help='The labels for the legend. Should be in the same order as `ls` lists the simulation result directories in the experiment directory.')
    args = parser.parse_args()

    exp_output = f"dynamic-id{args.dataset}-{args.experiment}/"
    exp_base = args.basepath + exp_output
    list_of_files = [glob(exp_base + inode + '/READABLE*/0/C*/')[0] + metric_file_mapping[args.metric]['filename']
                     for inode in listdir(exp_base)
                     if args.algorithm == 'all' or args.algorithm in inode
                     if isdir(exp_base + inode)]
    list_of_files.sort()
    pp = pprint.PrettyPrinter(indent=4)
    pp.pprint(list_of_files)
    if not args.xlabel:
        xlabel = metric_file_mapping[args.metric]['xlabel']
    if not args.ylabel:
        ylabel = metric_file_mapping[args.metric]['ylabel']

    pcn.line_plot_from_list(list_of_files,
                            xlabel=xlabel,
                            ylabel=ylabel,
                            running_avg=args.running_avg,
                            x_range=metric_file_mapping[args.metric]['x_range'],
                            y_range=metric_file_mapping[args.metric]['y_range'],
                            legend_labels=args.legend)
