#!/bin/bash

LOG_DIR=logs
ATTACK=attack_common.py

usage() {
  echo "Usage: $0 [start|stop|status]" 1>&2
  exit 1
}

stop() {
  ipcluster stop
  echo "ipcluster killed."

  ps -ef | grep ipyparallel | grep -v grep | awk '{print $2}' | xargs kill -9
  ps -ef | grep ipcluster | grep -v grep | awk '{print $2}' | xargs kill -9
  ps -ef | grep attack | awk '{print $2}' | xargs kill -9
  ps -ef | grep java | awk '{print $2}' | xargs kill -9
  echo "attack killed."
  exit 0
}

status() {
  lines=$(ps -ef | grep ipcluster | wc -l)
  if [ $lines -gt 2 ]; then
    echo "ipcluster is running..."
  else
    echo "ipcluster is not running..."
  fi

  lines=$(ps -ef | grep attack | wc -l)
  if [ $lines -gt 2 ]; then
    echo "attack is running..."
  fi

  exit 0
}

start() {
  ENGINES="$1"
  nohup ipcluster start -n ${ENGINES} &> ${LOG_DIR}/ipcluster.out &
  exec tail -f ${LOG_DIR}/ipcluster.out
}

attack() {
  ATTACK_TYPE="$1"
  mvn clean install
  nohup python ${ATTACK} ${ATTACK_TYPE} &> ${LOG_DIR}/attack.out &
  echo "${LOG_DIR}/attack.out"
  exit 0
}

mkdir -p ${LOG_DIR}
while :; do
  case "$1" in
    start)
      start "$2"
      ;;
    stop)
      stop
      ;;
    status)
      status
      ;;
    attack)
      attack "$2"
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))



