#!/bin/bash

ENGINES=11
LOG_DIR=logs
ATTACK=attack-1.py

usage() {
    echo "Usage: $0 [start|stop|status]" 1>&2
    exit 1
}

stop() {
    ipcluster stop
    echo "ipcluster killed."

    ps -ef | grep attack | awk '{print $2}' | xargs kill -9
    ps -ef | grep java | awk '{print $2}' | xargs kill -9
    echo "attack killed."
    exit 0
}

status() {
    lines=$(ps -ef | grep ipcluster | wc -l)
    if [ $lines -gt 2 ]; then
	echo "ipcluster is running..."
    else
	echo "ipcluster is not running..."
    fi

    lines=$(ps -ef | grep attack | wc -l)
    if [ $lines -gt 2 ]; then
	echo "attack is running..."
    fi

    exit 0
}

start() {
    nohup ipcluster start -n ${ENGINES} &> ${LOG_DIR}/ipcluster.out &
    exec tailf ${LOG_DIR}/ipcluster.out            
}

attack() {
    nohup python ${ATTACK} &> ${LOG_DIR}/attack-1.out &
    echo "${LOG_DIR}/attack-1.out"
    exit 0
}

while :; do
    case "$1" in
        start)
	    start
            ;;
        stop)
	    stop
            ;;
	status)
	    status
	    ;;
	attack)
	    attack
	    ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))



