#!/bin/bash

LOG_DIR=logs
ATTACK_LOG=${LOG_DIR}/attack-`hostname`-`date +%m-%d-%y`.out
ATTACK=attack_common.py

usage() {
  echo "Usage: $0 [start|stop|status]" 1>&2
  exit 1
}

stop() {
  ipcluster stop
  echo "ipcluster killed."

  ps -ef | grep ipyparallel | grep -v grep | awk '{print $2}' | xargs kill -9
  ps -ef | grep ipcluster | grep -v grep | awk '{print $2}' | xargs kill -9
  ps -ef | grep attack | awk '{print $2}' | xargs kill -9
  ps -ef | grep java | awk '{print $2}' | xargs kill -9
  echo "attack killed."
  exit 0
}

status() {
  lines=$(ps -ef | grep ipcluster | grep -v grep | wc -l)
  if [ $lines -gt 0 ]; then
    echo "ipcluster is running..."
  else
    echo "ipcluster is not running..."
  fi

  lines=$(ps -ef | grep attack | grep -v grep | wc -l)
  if [ $lines -gt 0 ]; then
    echo "attack is running..."
  fi

  exit 0
}

start() {
  ENGINES="$1"
  ipcluster start --daemonize=True -n "${ENGINES}"
  exec tail -f ~/.ipython/profile_default/log/ipcluster-*.log
}

attack() {
  ATTACK_TYPE="$1"
  # mvn clean install
  nohup python ${ATTACK} ${ATTACK_TYPE} &> ${ATTACK_LOG} &
  echo "${ATTACK_LOG}"
  exit 0
}

mkdir -p ${LOG_DIR}
while :; do
  case "$1" in
    start)
      start "$2"
      ;;
    stop)
      stop
      ;;
    status)
      status
      ;;
    attack)
      attack "$2"
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))



