base_topology: scalefree
connection_parameter: 2
force: true
id: '58'
log_level: error
min_channel_balance: 0
multiplier_probability: 1.0
name: id58-synthetic-poisson-nodes-10000-txs-exponential-100000-scalefree2-mult-1.0-prob-1.0
node_count: 10000
nographcalcs: false
noplots: false
showtopology: false
specfile: null
tx_count: 100000
tx_inclusion_probability: 1.0
tx_participant_distribution: poisson
tx_value_distribution: exponential
value_multiplier: 1.0
